# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "cvdabbeele/c1-app-sec-moneyx"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "cvdabbeele/c1-app-sec-moneyx"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "ls"
      - >-
              docker run -v /var/run/docker.sock:/var/run/docker.sock
              deepsecurity/smartcheck-scan-action
              --image-name="$REPOSITORY_URI:$TAG"
              --findings-threshold="{\"malware\":0,\"vulnerabilities\":{\"defcon1\":0,\"critical\":100,\"high\":100},\"contents\":{\"defcon1\":0,\"critical\":0,\"high\":1},\"checklists\":{\"defcon1\":0,\"critical\":0,\"high\":0}}"
              --preregistry-host="$SMARTCHECK_HOST:5000"
              --smartcheck-host="$SMARTCHECK_HOST"
              --smartcheck-user="$SMARTCHECK_USER"
              --smartcheck-password="$SMARTCHECK_PWD"
              --insecure-skip-tls-verify="true"
              --preregistry-scan
              --preregistry-user="$PRE_SCAN_USER"
              --preregistry-password="$PRE_SCAN_PWD"

    stage: "test"
